### ISSUE TITLE
webpack load error while running karma test

### ISSUE THREAD

**Issue by ggibsen** [ggibsen/peer-survey-2#1]
using latest dev dependencies as of ~ 5/10/17, getting this error

```WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
  at webpack (/Users/greg/projects/peerSurvey/node_modules/webpack/lib/webpack.js:19:9)
  at new Plugin (/Users/greg/projects/peerSurvey/node_modules/karma-webpack/lib/karma-webpack.js:67:16)```

when running gulp test

**Comment by ggibsen** [comment]
mean@0.9.1 /Users/greg/projects/peerSurvey
├── webpack@2.4.1 
└── karma-webpack@2.0.3

==============================================================================
https://david-dm.org/webpack/karma-webpack

karma-webpack --> calls webpack  (we need webpack 2.5 per david dm site)
==============================================================================

npm uninstall webpack
npm install --save-dev webpack@2.5.0


may 13th, clear npm cache, did fresh install and updates of some of proj modules
:peerSurvey greg$ npm list|grep webpack
├─┬ karma-webpack@2.0.3
│ └── webpack-dev-middleware@1.10.2 deduped
├─┬ webpack@2.5.1
│ ├─┬ webpack-sources@0.2.3
├─┬ webpack-dev-middleware@1.10.2
├─┬ webpack-dev-server@2.4.4
│ ├── webpack-dev-middleware@1.10.2 deduped
├─┬ webpack-hot-middleware@2.18.0
└─┬ webpack-stream@3.2.0
  └─┬ webpack@1.15.0
    └─┬ webpack-core@0.6.9


using webpack 2.5.1, still get  load error


I THINK WHAT I NEED IS A compatible version of frequent updates to webpack to work w/ the infrequent updates of karma-webpack
karma-webpack
	2.0.3 was mar 15th
webpack
	v1.15.0 apr 15
	2.3.1 mar 22


npm uninstall webpack --save-dev
npm install --save-dev webpack@2.5.0



otw node_modules/karma-webpack/package.json
"peerDependencies": {
    "webpack": "^1.1.0 || ^2 || ^2.1.0-beta.0 || ^2.2.0-rc.0"
  },
npm view webpack versions|grep 2.2  
# i actually downgraded from 2.3.0 (still getting error)
npm install webpack@2.2.1 --save-dev

STILL got load error...  next i'll try 1.15.0 webpack ??!?!

WORKS!! :)
